const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    adminId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      comment: null,
      primaryKey: true,
      field: "adminId",
      autoIncrement: true,
    },
    fullName: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "fullName",
      autoIncrement: false,
    },
    email: {
      type: DataTypes.STRING(60),
      allowNull: true,
      validate: {
        isEmail: true,
      },
    },
    mobileNumber: {
      type: DataTypes.STRING(15),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "mobileNumber",
      autoIncrement: false,
    },
    countryCode: {
      type: DataTypes.STRING(5),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "countryCode",
      autoIncrement: false,
    },
    password: {
      type: DataTypes.STRING(255),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "password",
      autoIncrement: false,
    },
    otp: {
      type: DataTypes.STRING(150),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "otp",
      autoIncrement: false,
    },
    block: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "block",
      autoIncrement: false,
    },
    profilePicture: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "profilePicture",
      autoIncrement: false,
    },
    created: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "created",
      autoIncrement: false,
    },
    updated: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "updated",
      autoIncrement: false,
    },
    delete: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "delete",
      autoIncrement: false,
    },
    createdBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "createdBy",
      autoIncrement: false,
    },
    updatedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "updatedBy",
      autoIncrement: false,
    },
    deleteBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "deleteBy",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "admin",
    comment: "",
    indexes: [],
  };
  const AdminModel = sequelize.define("admin_model", attributes, options);
  return AdminModel;
};
