const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    courseId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      comment: null,
      primaryKey: true,
      field: "courseId",
      autoIncrement: true,
    },
    courseName: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "courseName",
      autoIncrement: false,
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "description",
      autoIncrement: false,
    },
    fee: {
      type: DataTypes.STRING(20),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "fee",
      autoIncrement: false,
    },
    duration: {
      type: DataTypes.STRING(20),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "duration",
      autoIncrement: false,
    },
      durationType: {
      type: DataTypes.ENUM("WEEK", "MONTH", "YEAR"),
      allowNull: true,
      defaultValue: "MONTH",
      comment: null,
      field: "durationType",
    },
    created: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "created",
      autoIncrement: false,
    },
    updated: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "updated",
      autoIncrement: false,
    },
    delete: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "delete",
      autoIncrement: false,
    },
    createdBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "createdBy",
      autoIncrement: false,
    },
    updatedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "updatedBy",
      autoIncrement: false,
    },
    deleteBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "deleteBy",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "course",
    comment: "",
    indexes: [],
  };
  const courseModel = sequelize.define("course_model", attributes, options);
  return courseModel;
};
