const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    enrollmentId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      comment: null,
      primaryKey: true,
      field: "enrollmentId",
      autoIncrement: true,
    },
    courseId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "courseId",
      autoIncrement: false,
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "userId",
      autoIncrement: false,
    },
    enrollmentDate: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "enrollmentDate",
      autoIncrement: false,
    },
    status: {
      type: DataTypes.ENUM("ACTIVE", "COMPLETED", "DROPPED"),
      allowNull: true,
      defaultValue: "ACTIVE",
      comment: null,
      field: "status",
    },
    enrollmentType: {
      type: DataTypes.ENUM("MONTHLY", "ANNUAL"),
      allowNull: true,
      defaultValue: "MONTHLY",
      comment: null,
      field: "enrollmentType",
    },
    amount: {
      type: DataTypes.STRING(20),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "amount",
      autoIncrement: false,
    },
    created: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "created",
      autoIncrement: false,
    },
    updated: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "updated",
      autoIncrement: false,
    },
    delete: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "delete",
      autoIncrement: false,
    },
    createdBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "createdBy",
      autoIncrement: false,
    },
    updatedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "updatedBy",
      autoIncrement: false,
    },
    deleteBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "deleteBy",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "enrollment",
    comment: "",
    indexes: [],
  };
  const enrollmentModel = sequelize.define("enrollment_model", attributes, options);
  return enrollmentModel;
};
