const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    paymentId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      comment: null,
      primaryKey: true,
      field: "paymentId",
      autoIncrement: true,
    },
    enrollmentId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "enrollmentId",
      autoIncrement: false,
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "userId",
      autoIncrement: false,
    },
    amount: {
      type: DataTypes.STRING(20),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "amount",
      autoIncrement: false,
    },
    paidAmount: {
      type: DataTypes.STRING(20),
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "paidAmount",
      autoIncrement: false,
    },
    paymentMode: {
      type: DataTypes.ENUM("CASE", "ONLINE", "UPI"),
      allowNull: true,
      defaultValue: "CASE",
      comment: null,
      field: "paymentMode",
    },
    note: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "note",
      autoIncrement: false,
    },
    startDate: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "startDate",
      autoIncrement: false,
    },
    endDate: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "endDate",
      autoIncrement: false,
    },
    created: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "created",
      autoIncrement: false,
    },
    updated: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: sequelize.literal("CURRENT_TIMESTAMP"),
      comment: null,
      primaryKey: false,
      field: "updated",
      autoIncrement: false,
    },
    delete: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "delete",
      autoIncrement: false,
    },
    createdBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "createdBy",
      autoIncrement: false,
    },
    updatedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "updatedBy",
      autoIncrement: false,
    },
    deleteBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      comment: null,
      primaryKey: false,
      field: "deleteBy",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "payment",
    comment: "",
    indexes: [],
  };
  const paymentModel = sequelize.define("payment_model", attributes, options);
  return paymentModel;
};
